In [1]:
import pandas as pd
import seaborn as sns
from sklearn.linear_model import LinearRegression

In [2]:
House_price = pd.read_csv("HousePricePrediction.csv")

In [3]:
House_price.head()

,Id,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice
0,0,60,RL,8450,Inside,1Fam,5,2003,2003,VinylSd,0.0,856.0,208500.0
1,1,20,RL,9600,FR2,1Fam,8,1976,1976,MetalSd,0.0,1262.0,181500.0
2,2,60,RL,11250,Inside,1Fam,5,2001,2002,VinylSd,0.0,920.0,223500.0
3,3,70,RL,9550,Corner,1Fam,5,1915,1970,Wd Sdng,0.0,756.0,140000.0
4,4,60,RL,14260,FR2,1Fam,5,2000,2000,VinylSd,0.0,1145.0,250000.0

In [24]:
X= House_price.drop(columns =["Id"])
House_price['SalePrice'] = House_price['SalePrice'].fillna(
  House_price['SalePrice'].mean()) 

# Drop records with null values
House_price = House_price.dropna()

House_price.isnull().sum()
House_price.head()

,Id,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice
0,0,60,RL,8450,Inside,1Fam,5,2003,2003,VinylSd,0.0,856.0,208500.0
1,1,20,RL,9600,FR2,1Fam,8,1976,1976,MetalSd,0.0,1262.0,181500.0
2,2,60,RL,11250,Inside,1Fam,5,2001,2002,VinylSd,0.0,920.0,223500.0
3,3,70,RL,9550,Corner,1Fam,5,1915,1970,Wd Sdng,0.0,756.0,140000.0
4,4,60,RL,14260,FR2,1Fam,5,2000,2000,VinylSd,0.0,1145.0,250000.0

In [36]:
X = House_price.drop(['SalePrice'], axis=1)
y = House_price['SalePrice']
X = pd.get_dummies(X, drop_first=True)

## 2. AAPKA TARIQA (Har column ki apni correct dictionary ke saath):
#X["MSZoning"] = X["MSZoning"].map({"RL": 1, "RM": 0, "C (all)": 2, "FV": 3, "RH": 4})
#X["LotConfig"] = X["LotConfig"].map({"Inside": 0, "Corner": 1, "FR2": 2, "CulDSac": 3, "FR3": 4})
#X["BldgType"] = X["BldgType"].map({"1Fam": 0, "2fmCon": 1, "Duplex": 2, "TwnhsE": 3, "Twnhs": 4})
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=0)

In [37]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [42]:
y_predict = model.predict(X_test)

In [43]:
y_predict

array([191873.41740727, 257778.68469015, 172460.43364452, 179376.11495513,
       206252.32732904, 198329.95607144, 122175.41166554, 156855.47314711,
       191181.92665476, 205524.82071299, 150729.65740342, 218229.2351498 ,
       175615.46105837, 146346.60292468, 199887.70830751, 140258.78190135,
       168601.04014278, 162887.26404965, 198981.58427329, 197980.05677649,
       195146.60077208, 134224.03668337, 212718.97830052, 171151.94339045,
       133882.54225388, 155188.31231658, 148382.62546722, 173220.35633836,
       162501.06568228, 148228.46307233, 165586.38726125, 190497.1874872 ,
       162509.13695476, 193172.54665896, 173346.0330102 , 196342.71998094,
       141508.35256335, 164645.70767191, 169107.2391194 , 169901.24840713,
       213745.69814209, 227040.14028434, 225237.52901175, 140810.61150836,
       199725.25941672, 222349.95782023, 218740.11204403, 112602.13632385,
       170895.23173367, 195306.67078542, 199793.28016071, 193574.9626042 ,
       125058.26705931, 153329.07100534, 197809.45466378, 152963.43404022,
       134788.05262246, 221087.19657315, 181999.0093682 , 198613.99165701,
       206395.06785776, 167635.8242723 , 132449.07468877, 165404.71157596,
       192439.14115445, 193867.2480782 , 103426.63176785, 152990.05938018,
       158897.24217849, 179283.36289652, 161229.54246583, 201307.14365299,
       183392.73783229, 209373.13988973, 178980.71377584, 152986.00651236,
       196436.49137104, 187489.57271378, 109910.8716747 , 204821.49337407,
       147206.86112601, 186451.6312502 , 200768.07808151, 173364.25221343,
       152324.10086246, 166637.96392528, 155655.58565631, 205245.50354756,
       155925.86558152, 166615.29228064, 171126.31009477, 201247.38127906,
       178158.0940269 , 154202.60539257, 183010.58375579, 140900.96534416,
       165274.56554973, 158075.65206548, 179273.03192633, 131091.42996414,
       159057.11287444, 161915.03167169, 182722.37044907, 196971.28706221,
       146320.61739586, 208364.08784182, 200922.50069193, 203390.27998276,
       137002.5663667 , 189068.62295578, 126491.16153214, 239658.01404447,
       189963.87236623, 203400.22368223, 195362.97379848, 182227.08660122,
       215637.89888399, 162304.15172291, 222961.82317584, 156483.72039036,
       248576.05463499, 236403.73034323, 188397.1834693 , 157441.47875385,
       163267.54735717, 211610.66134789, 180651.55170872, 184079.31435905,
       162213.55913888, 174452.4521703 , 138879.56457933, 180132.56620691,
       219290.90185829, 184647.38116452, 141495.14311876, 160960.20220776,
       217372.59573389, 154252.51236187, 181286.79057409, 223661.43370444,
       141470.74016074, 184405.39288846, 190232.13345107, 184733.91471055,
       190793.13253381, 185466.06898382, 203845.52041704, 173548.75581063,
       123098.50168852, 152723.92410626, 206861.95968057, 193642.50939463,
       161933.94857217, 155043.69665132, 134681.65868904, 129129.75716303,
       153765.07695187, 135087.78066583, 201783.31260048, 195127.12824802,
       162715.62678786, 142693.24383487, 194923.09785994, 163772.82863005,
       167277.04820684, 215218.69460596, 211982.89027392, 192788.00388816,
       217169.71232846, 192584.16528873, 192531.73059906, 141242.13363069,
       169929.70812124, 229154.96153722, 189172.13557746, 171744.67569966,
       166270.81704566, 195600.75311878, 223397.4704235 , 212176.7445798 ,
       139313.31593417, 184469.30429285, 199383.01334197, 165054.54513572,
       207732.45888335, 211805.48657619, 193948.26933464, 224566.82678214,
       125538.11163258, 182245.91902628, 162407.95625699, 149537.99802187,
       185609.4317932 , 159409.79106927, 164100.9285662 , 215930.09324487,
       247776.93815608, 182689.5151472 , 152321.18096154, 145106.75969236,
       205595.55876778, 177178.19522562, 197879.689426  , 177428.35198669,
       172574.55717615, 150360.29756882, 186769.03197292, 206656.35452804,
       165104.84926954, 127810.11939975, 151568.44563724, 182781.76564992,
       212612.18622555, 164035.89726123, 153257.37263242, 181398.49294307,
       168168.2924289 , 177963.205656  , 191085.52895598, 196827.31000535,
       141036.2072803 , 165231.84769259, 163246.75665731, 161304.53557404,
       162391.75227408, 228069.12379017, 202233.0590328 , 155426.84714103,
       220702.22066655, 171899.35102769, 157295.08540399, 131160.15334942,
       180988.01247169, 161845.79983754, 148913.77426088, 204583.08980672,
       141656.82506205, 198055.83348653, 203096.98139773, 153766.13248903,
       192877.98615502, 188619.4076815 , 163999.02905524, 129035.65700587,
       165149.41673425, 154220.77147769, 113178.95646575, 191789.34305344,
       200745.72345476, 243792.92627066, 197444.28000845, 168522.67752225,
       148449.43366261, 235175.61541887, 209722.34680116, 156701.14975331,
       201389.49254086, 225431.74950639, 199544.19110087, 195001.55647991,
       185377.28297658, 201504.17157814, 167940.85674926, 193202.3448679 ,
       229380.25359326, 168566.86167483, 137143.73915147, 162125.98202711,
       214157.76688859, 124054.78611046, 109734.11505598, 227305.60897279,
       201912.22357572, 158200.73020119, 136279.04644043, 246722.83886328,
       249241.24852211, 169244.8140479 , 186923.99350687, 156116.0328459 ,
       157038.61552891, 188313.80825022, 201577.00194324, 208594.71101633,
       160911.83634959, 186763.67726372, 276982.04862522, 179062.82573083,
       216890.13287611, 178314.78845004, 140359.71406116, 208792.84783439,
       220513.29550784, 169583.53332437, 189664.8702076 , 156992.96517699,
       210713.91603174, 189203.35367898, 201370.52531686, 213739.0037726 ,
       161870.30107544, 116403.695347  , 211049.23775518, 181022.94331285,
       291103.57300239, 185432.10462514, 150321.55548871, 216798.22291018,
       151768.11102711, 186047.69514251, 178802.56773677, 193136.41537118,
       150559.62880427, 217637.40446382, 164806.00300981, 159619.89279886,
       196677.84369045, 163848.97342771, 241134.90856414, 155699.7955328 ,
       194806.59596547, 135112.15713395, 186762.09354033, 107670.68968787,
       207717.62091033, 196971.6101118 , 209211.3261477 , 133671.17835479,
       194485.39614322, 164110.07219779, 161006.93574454, 267311.8186916 ,
       151491.85735273, 223082.8318011 , 222422.46947887, 168288.98718517,
       214347.38841972, 170383.91801525, 201455.84724701, 197447.87261929,
       190595.66935784, 124185.93541909, 227281.36867606, 152467.80988018,
       160863.43586945, 162903.87760356, 153281.86927074, 135902.85092196,
       209259.66859704, 175742.83867026, 193694.88608244, 187951.31897189,
       226855.94161521, 133084.36107304, 199649.96527211, 177466.31309428,
       172512.10678227, 150455.70405437, 231925.05424398, 207544.86170694,
       221315.70328463, 199713.04651244, 150920.90474014, 190014.24399102,
       144598.92011053, 216806.00704653, 227629.11755751, 202989.39812516,
       154437.75719949, 191155.28516847, 205123.43836881, 192187.68694925,
       164805.11137902, 173145.29000332, 243953.65520458, 157474.48928684,
       166945.33582078, 214497.77437323, 144070.77192646, 208758.55549001,
       163623.10215922, 162860.43237879, 155545.74124829, 170878.6785166 ,
       149867.11831549, 199274.59165872, 200546.37125112, 197387.45777922,
       206480.05224571, 179616.657891  , 195379.95154902, 201382.5638801 ,
       213315.89045043, 218611.90340925, 198232.43505795, 145421.57679322,
       168481.82031923, 144646.94697115, 198819.42920288, 231679.19709569,
       229569.99144052, 181008.73332684, 197355.19558248, 214652.57222671,
       174815.79421964, 197201.97918862, 178822.78365259, 168744.128861  ,
       175180.75283395, 161066.04979513, 233612.29981603, 201979.18581665,
       188467.67022093, 153080.61255349, 146411.75691639, 119293.50052268,
       211543.95653926, 161840.21396402, 163604.38969889, 168586.39568113,
       184191.57627732, 178117.33759172, 153403.00588747, 183370.88343716,
       190632.00301476, 209799.50533352, 160916.77570544, 209394.37856829,
       214542.65473809, 152960.06905188, 165656.13552556, 202296.94309181,
       171717.68870066, 149838.17181577, 140318.12928445, 178422.89819521,
       198415.99651465, 165001.41041239, 127381.33363265, 135317.25065919,
       184505.45792433, 186433.73849028, 166337.93478441, 178921.60151335,
       138886.69215697, 228434.74097279, 171698.60522637, 167344.57891871,
       187806.81559433, 142645.91428403, 201996.17225678, 199496.1219074 ,
       170173.84460514, 194097.66399973, 145345.41372829, 196310.35409118,
       148664.72305675, 146361.80848473, 154249.18226552, 175602.41485649,
       183637.74159816, 200165.96135451, 218983.58350671, 207450.06789377,
       174493.61152164, 158324.19814834, 219206.05250122, 269054.05361683,
       149895.49354221, 154294.60655758, 184639.97568418, 226982.74075855,
       115048.56438894, 182861.21262846, 195951.59071385, 194441.48113843,
       259005.17897317, 150438.72678108, 189537.19366495, 182559.07880991,
       211984.20195668, 220158.64131299, 167537.57451287, 200478.21666173,
       247295.24480963, 230501.66225406, 171131.56030795, 153358.84515768,
       213032.43547834, 198467.00700352, 167718.01085878, 193883.50368853,
       134611.72254407, 197763.7129053 , 186595.99255511, 227443.47953957,
       183033.67374225, 146725.28176532, 156794.57584638, 160030.76443263,
       159173.81360824, 187861.68888916,  98602.24430059, 217681.80412209,
       193554.42901491, 206031.4997023 , 201591.04252116, 226969.61865676,
       124666.48267647, 198365.89899642, 210221.82166714, 201638.96012689,
       208390.27591038, 201694.09880497, 205364.30463831, 211021.85975347,
       179216.64500967, 130505.21999659, 199702.56336313, 172911.72653509,
       202284.68674762, 215117.56055163, 202265.57696961, 149880.87790043,
       235069.59645908, 165016.62122169, 162254.07781746, 191591.10697222,
       213630.97246992, 174913.00143753, 146725.5073641 , 125022.73556016,
       204598.30148183, 175466.25631973, 182051.30326721, 216309.99629703,
       158497.10494221, 166442.37979584, 161302.12847038, 192813.22974559,
       152167.16102292, 191210.6690793 , 202227.95591603, 177919.02360739,
       152283.66448676, 206645.50338796, 187197.30934266, 140916.56385235,
       189209.94482245, 193167.60936816, 147144.08357263, 175996.91432127,
       159998.30899017, 140287.56876077, 212748.58723351, 158402.18479845,
       176374.08916818, 192834.97055512, 169070.72011092, 223844.4804038 ,
       166145.41136386, 170325.40096835, 114889.31048892, 220420.94485051,
       194766.23884876, 172378.27735479, 220148.21117316, 205331.08762351,
       134554.09812121, 125001.25731347, 213133.33551813, 203479.33399698,
       174184.82217585, 213004.93285251, 181224.30699939, 202805.9200454 ,
       188688.12220088, 126652.04533027, 168787.10346894, 215501.93648881,
       157488.91213359, 225788.47384915, 177368.66481717])